sudo: required

notifications:
  email: false

os:
  - linux
  - osx

language: ruby
rvm:
  - 2.5.1

services:
  - docker

script:
  - ./test/run_test.rb

deploy:
  provider: script
  script: if [ "$TRAVIS_OS_NAME" = "linux" ]; then sh deploy.sh; fi
  on:
    all_branches: true
    condition: $TRAVIS_PULL_REQUEST = false
