sudo: required

notifications:
  email: false

os:
  - linux
  - osx

language: ruby
rvm:
  - 2.5.1

services:
  - docker

script:
  - ./test/run_test.rb

deploy:
  provider: script
  script: deploy.sh
  on:
    branch: master
    os: linux
