sudo: required

notifications:
  email: false

os:
  - linux
  - osx

language: ruby
rvm:
  - 2.5.1

services:
  - docker

script:
  - ./test/run_test.rb

deploy:
  provider: script
  script: sh deploy.sh
  on:
    condition: ($TRAVIS_OS_NAME = linux) AND ($TRAVIS_PULL_REQUEST = false) AND (branch = master) AND (tag IS present)
